# Generated by Django 5.2.17 on 2026-09-11 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordinal', models.BooleanField(default=False, verbose_name='ordinal')),
            ],
            options={
                'verbose_name': 'domínio',
                'verbose_name_plural': 'domínios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
                'ordering': ['categoria', 'ordem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('numerica', 'numérica'), ('nominal', 'categórica nominal'), ('ordinal', 'categórica ordinal'), ('booleana', 'booleana'), ('data', 'data'), ('texto', 'texto livre')], max_length=10, verbose_name='tipo')),
                ('definicao', models.CharField(blank=True, max_length=220, verbose_name='definição')),
                ('unidade', models.CharField(blank=True, max_length=30, verbose_name='unidade canônica')),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='mínimo plausível')),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='máximo plausível')),
                ('tabela_referencia', models.CharField(blank=True, max_length=40, verbose_name='tabela de referência')),
                ('vida_util_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='vida útil em dias')),
                ('derivada', models.BooleanField(default=False, verbose_name='derivada')),
                ('sensivel', models.BooleanField(default=False, verbose_name='sensível')),
                ('busca', models.CharField(default='', editable=False, max_length=200, verbose_name='texto de busca')),
                ('dominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variaveis', to='catalogo.dominio')),
                ('origem', models.ManyToManyField(blank=True, related_name='derivadas', to='catalogo.variavel', verbose_name='calculada a partir de')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variaveis', to='catalogo.subcategoria')),
            ],
            options={
                'verbose_name': 'variável',
                'verbose_name_plural': 'variáveis',
                'ordering': ['subcategoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SlugField(max_length=60, verbose_name='valor')),
                ('rotulo', models.CharField(max_length=120, verbose_name='rótulo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='catalogo.dominio')),
            ],
            options={
                'verbose_name': 'opção de domínio',
                'verbose_name_plural': 'opções de domínio',
                'ordering': ['dominio', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('dominio', 'valor'), name='valor_unico_por_dominio')],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'codigo'), name='codigo_unico_por_categoria'),
        ),
    ]
