# Generated by Django 5.2.17 on 2026-09-11 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('condicao', models.CharField(max_length=120, verbose_name='condição estudada')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='rascunho', max_length=10, verbose_name='situação')),
                ('participantes_necessarios', models.PositiveIntegerField(blank=True, null=True, verbose_name='participantes necessários')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudos', to=settings.AUTH_USER_MODEL, verbose_name='pesquisador')),
            ],
            options={
                'verbose_name': 'estudo',
                'verbose_name_plural': 'estudos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(choices=[('igual', '='), ('diferente', '≠'), ('menor', '<'), ('menor_igual', '≤'), ('maior', '>'), ('maior_igual', '≥'), ('entre', 'entre'), ('e', 'é'), ('nao_e', 'não é'), ('esta_em', 'está em'), ('nao_esta_em', 'não está em'), ('verdadeiro', 'é verdadeiro'), ('falso', 'é falso'), ('antes', 'antes de'), ('depois', 'depois de')], max_length=12, verbose_name='operador')),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor')),
                ('valor_numero_ate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='até')),
                ('valor_data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('valor_data_ate', models.DateField(blank=True, null=True, verbose_name='até')),
                ('precisao', models.CharField(choices=[('dia', 'data completa'), ('mes', 'mês e ano'), ('ano', 'apenas o ano')], default='dia', max_length=3, verbose_name='precisão da data')),
                ('opcoes', models.ManyToManyField(blank=True, related_name='criterios', to='catalogo.opcaodominio', verbose_name='valores')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='catalogo.variavel')),
                ('estudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='estudos.estudo')),
            ],
            options={
                'verbose_name': 'critério',
                'verbose_name_plural': 'critérios',
                'ordering': ['variavel__codigo'],
            },
        ),
    ]
